/// One decoder, as a page. The registry id in `../super-radio` is the slug
/// wherever the two can agree, so a scanner line on the page is one that runs.
export interface Decode {
  slug: string;
  name: string;
  /// The other names people search for, listed on the page and in the meta.
  aka?: string;
  kicker: string;
  summary: string;
  body: string[];
  /// What a decoded frame actually gives you, one field per line.
  fields: string[];
  hardware: string;
  views: string[];
  cli?: string;
  /// What it does not do yet, where leaving it out would mislead.
  gap?: string;
  /// Slugs of the pages worth reading next.
  related: string[];
  band: string;
}

export const DECODES: Decode[] = [
  {
    slug: 'adsb',
    name: 'ADS-B and Mode S',
    aka: 'dump1090, 1090 MHz, Mode S, secondary radar',
    kicker: '1090 MHz',
    summary:
      'Aircraft on a map with callsign, altitude, speed, track and position, read off the 1090 MHz downlink alongside everything else in the span.',
    body: [
      'Mode S is the transponder reply every airliner sends, and ADS-B is the part of it that carries a position the aircraft worked out for itself. WaveShark reads both span-wide rather than on a channel, because a Mode S frame is shorter than a detector frame, and puts each aircraft on the map with a track table beside it.',
      'A single position frame from an aircraft you have no pair for still places it, as long as the receiver knows where it is: give it <code>--location</code> or set the station position and the surface position decoding has its reference. A mark drawn from one frame is hollow and never joins a trail, so a guess never becomes a track.',
      'Checked against dump1090 on the same recordings, which is the only way to know a decoder is right rather than merely confident.',
    ],
    fields: [
      'ICAO address, and the callsign when the aircraft sends one',
      'Altitude, ground speed, heading and vertical rate',
      'Position, with the range ring drawn from your antenna',
      'Squawk, and the emergency codes as they are set',
    ],
    hardware: 'Any RTL-SDR, and an antenna cut for 1090 MHz',
    views: ['Map', 'Data links', 'Devices'],
    cli: '<span class="c">$</span> waveshark --tune 1090 --location 53.34,-6.26 --flights',
    related: ['uat', 'acars', 'vdl2', 'aero'],
    band: '1090-mhz',
  },
  {
    slug: 'uat',
    name: 'UAT at 978 MHz',
    aka: 'UAT978, ADS-B UAT, FIS-B, TIS-B',
    kicker: '978 MHz',
    summary:
      'The light aircraft that never appear on 1090, and the ground stations uplinking weather and traffic to them.',
    body: [
      'UAT is the other ADS-B link, used in the United States by aircraft below 18,000 feet. Reading it is how the general aviation traffic that is invisible on 1090 MHz gets onto the map, and the airframes on it are the interesting ones: gliders, trainers, crop dusters.',
      'The ground stations transmit too. Their uplink carries the weather and traffic picture being sent to cockpits, which is a broadcast service with nothing encrypted about it.',
    ],
    fields: [
      'ICAO address, callsign, position, altitude and velocity',
      'Emitter category, so a glider is not drawn as a jet',
      'Ground station uplink: the weather and traffic products it is sending',
    ],
    hardware: 'Any RTL-SDR; the same antenna as 1090 MHz works',
    views: ['Map', 'Data links'],
    cli: '<span class="c">$</span> waveshark --tune 978 --location 40.71,-74.01 --flights',
    related: ['adsb', 'acars', 'vdl2'],
    band: '1090-mhz',
  },
  {
    slug: 'acars',
    name: 'ACARS',
    aka: 'acarsdec, airline datalink, 131.550 MHz',
    kicker: '129-137 MHz',
    summary:
      'The text messages crews and airlines send each other over VHF: position reports, fuel figures, technical faults and free text.',
    body: [
      'ACARS is the older of the two VHF datalinks and still the busiest in most of the world. Each message names the aircraft registration, the flight number and the label saying what kind of message it is, and the body is often plain enough to read without a manual.',
      'WaveShark reads it across the data half of the airband rather than on one channel, so a message on a company frequency you did not know about is caught with the rest. Messages land in the message view and the link view, and are written down a file a day.',
      'Checked against acarsdec on the same recordings.',
    ],
    fields: [
      'Aircraft registration and flight number',
      'Label and block id, which say what kind of message it is',
      'The message text, where the airline sends it in clear',
      'Downlink or uplink, and the station that sent it',
    ],
    hardware: 'Any RTL-SDR, with an airband antenna',
    views: ['Messages', 'Data links', 'Map'],
    cli: '<span class="c">$</span> waveshark --tune 131.55 --mode am --messages',
    related: ['vdl2', 'aero', 'adsb'],
    band: 'airband',
  },
  {
    slug: 'vdl2',
    name: 'VDL Mode 2',
    aka: 'dumpvdl2, VDL2, 136.975 MHz, AVLC',
    kicker: '136.7-137 MHz',
    summary:
      'The datalink most European traffic now uses, carrying the same airline messages as ACARS at eight times the rate.',
    body: [
      'VDL Mode 2 replaced ACARS on most European fleets and much of the rest. It is D8PSK at 31,500 bits a second inside a 25 kHz channel, with AVLC frames underneath carrying ACARS messages and ATN traffic.',
      'The link view is the right place for it: one row per aircraft and ground station pair, with the frames that passed between them opening underneath. 136.975 MHz is the common channel, but the whole allocation is read at once.',
      'Checked against dumpvdl2 on the same recordings.',
    ],
    fields: [
      'Aircraft ICAO address and registration',
      'Ground station address, and which side sent the frame',
      'The ACARS message carried inside, with its label and text',
      'Frame type, so link management is separated from traffic',
    ],
    hardware: 'Any RTL-SDR, with an airband antenna',
    views: ['Data links', 'Messages', 'Map'],
    cli: '<span class="c">$</span> waveshark --tune 136.975 --links',
    related: ['acars', 'adsb', 'aero'],
    band: 'airband',
  },
  {
    slug: 'aero',
    name: 'Inmarsat Aero',
    aka: 'satellite ACARS, SatCom, L band aero',
    kicker: '1545-1555 MHz',
    summary:
      'The satellite half of airline datalink: the same messages as ACARS, sent where there is no VHF ground station to hear.',
    body: [
      'Over an ocean or a desert an aircraft has no VHF station in range, so its datalink goes up to an Inmarsat satellite instead. Because the satellite is geostationary, the downlink is a fixed signal from a fixed direction, which makes it one of the easiest satellite receptions there is once you have a patch antenna and a low noise amplifier.',
      'WaveShark reads the P channel signal units and the messages carried on them, which appear in the message view beside the VHF ones rather than in a tool of their own.',
    ],
    fields: [
      'Aircraft identity, where the message carries it',
      'The ACARS message and its label',
      'The signal unit type, on the P channel',
    ],
    hardware: 'RTL-SDR, an L band patch antenna and an LNA',
    views: ['Messages', 'Data links'],
    cli: '<span class="c">$</span> waveshark --tune 1545.0 --messages',
    related: ['stdc', 'acars', 'vdl2'],
    band: 'l-band',
  },
  {
    slug: 'stdc',
    name: 'Inmarsat STD-C',
    aka: 'EGC, SafetyNET, NCS, maritime safety',
    kicker: 'L band',
    summary:
      'EGC and SafetyNET broadcasts to shipping: navigation warnings, weather, piracy reports and search and rescue calls.',
    body: [
      'STD-C is the message service every commercial vessel is required to carry. The Enhanced Group Call broadcasts on it are addressed to ocean areas rather than to ships, which is why they are readable: a navigational warning is meant to reach everybody in that sea area.',
      'The traffic is a running commentary on what is happening at sea, and it arrives in the message view with the pagers and the mesh text rather than in a separate window.',
    ],
    fields: [
      'Message priority, from routine to distress',
      'The service and the ocean area it was addressed to',
      'The message text in full',
      'Positions where the message carries them, drawn on the map',
    ],
    hardware: 'RTL-SDR, an L band patch antenna and an LNA',
    views: ['Messages', 'Map'],
    cli: '<span class="c">$</span> waveshark --tune 1541.45 --messages',
    related: ['ais', 'aero', 'epirb'],
    band: 'l-band',
  },
  {
    slug: 'ais',
    name: 'AIS',
    aka: 'vessel tracking, marine AIS, 161.975 MHz',
    kicker: 'Marine VHF',
    summary:
      'Vessel positions and identity on the same map as the aircraft, off the two AIS channels at once.',
    body: [
      'Every commercial vessel and most pleasure craft transmit AIS: who they are, where they are, where they are going and how fast. The two channels sit 50 kHz apart, and WaveShark reads both from one span rather than making you choose.',
      'A vessel is the same kind of track as an aircraft, so the map, the trails and the range rings behave the same way. Static reports fill in the name, the type and the destination as they arrive, which is why a vessel gains a name a minute after its first position.',
    ],
    fields: [
      'MMSI, and the vessel name and call sign from static reports',
      'Position, course over ground, speed and rate of turn',
      'Ship type, dimensions and draught',
      'Destination and estimated arrival, as entered by the crew',
    ],
    hardware: 'Any RTL-SDR, with a marine band antenna',
    views: ['Map', 'Devices', 'Data links'],
    cli: '<span class="c">$</span> waveshark --tune 162 --span 200',
    related: ['stdc', 'epirb', 'adsb'],
    band: 'marine-vhf',
  },
  {
    slug: 'epirb',
    name: 'COSPAS-SARSAT beacons',
    aka: 'EPIRB, PLB, ELT, 406 MHz distress beacon',
    kicker: '406 MHz',
    summary:
      'Distress beacon identities and the position they encode, drawn on the map the moment one transmits.',
    body: [
      'An EPIRB on a vessel, a PLB in a pocket and an ELT in an aircraft all transmit the same 406 MHz burst, roughly once every fifty seconds, carrying a coded identity and often a GPS position. In normal times you will hear a test burst rather than a real activation.',
      'The beacon message is read for its country code, its identity and its position, and the beacon appears on the map as a track like any other. The 121.5 MHz homing carrier is a separate, undecoded signal.',
    ],
    fields: [
      'Country code and beacon identity, including the hex id',
      'Beacon type: EPIRB, PLB or ELT',
      'Encoded position, where the beacon has a fix',
      'Whether the burst is a test or a live activation',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Map', 'Messages'],
    cli: '<span class="c">$</span> waveshark --tune 406.05 --span 200',
    related: ['ais', 'stdc', 'radiosondes'],
    band: 'uhf-400',
  },
  {
    slug: 'aprs',
    name: 'APRS',
    aka: 'AX.25 packet, Mic-E, 144.800 MHz, 144.390 MHz',
    kicker: '144.800 / 144.390 / 144.640 MHz',
    summary:
      'Packet stations, digipeaters, weather stations and vehicle trackers, with a KISS TNC so your own software can use the same radio.',
    body: [
      'APRS is AX.25 at 1200 baud carrying position, weather and text, on one calling frequency per region: 144.800 in Europe, 144.390 in North America, 144.640 in Japan. Mic-E compressed positions are read along with the plain ones.',
      'The interesting part for an existing station is <code>--kiss-listen</code>: WaveShark serves a KISS TNC, so Xastir, YAAC, Direwolf-style tooling or anything else that speaks KISS treats the SDR as its modem, and can key AX.25 back out through a radio that transmits.',
    ],
    fields: [
      'Source and destination call signs, and the digipeater path',
      'Position, course, speed and altitude, Mic-E included',
      'Weather report fields where the station sends them',
      'Status and message text, in the message view',
    ],
    hardware: 'Any RTL-SDR; transmitting needs a HackRF or LimeSDR',
    views: ['Map', 'Messages', 'Data links'],
    cli: '<span class="c">$</span> waveshark --tune 144.8 --mode nfm --kiss-listen 8001',
    related: ['meshtastic', 'rtty', 'morse'],
    band: 'amateur-vhf-uhf',
  },
  {
    slug: 'pocsag',
    name: 'POCSAG paging',
    aka: 'pager decoder, capcode, 512 1200 2400 baud',
    kicker: 'Wherever pagers are used',
    summary:
      'Pager messages in clear at 512, 1200 and 2400 bit/s, deduplicated because a paging network sends every page twice.',
    body: [
      'Paging is still how hospitals, fire services and site alarms reach people, and POCSAG carries the message as plain text with a capcode naming the pager it is for. A network usually repeats each page, so WaveShark folds the same words heard twice inside two minutes into one message with a count rather than showing you both.',
      'A pager channel is a pager channel wherever it sits, so the decoder is placed by shape rather than by band: point the receiver at the allocation your local network uses and it runs.',
      'Worth saying plainly: this traffic often carries medical and personal detail, and what you may lawfully receive and keep differs by country.',
    ],
    fields: [
      'Capcode and function bits',
      'Message text, or the numeric message',
      'Baud rate and the channel it arrived on',
      'A repeat count where the network sent the page more than once',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Messages', 'Devices'],
    cli: '<span class="c">$</span> waveshark --tune 153.35 --mode nfm --messages',
    related: ['flex', 'two-tone', 'mdc1200'],
    band: 'business-vhf-uhf',
  },
  {
    slug: 'flex',
    name: 'FLEX paging',
    aka: 'FLEX 1600 3200, Motorola paging',
    kicker: 'VHF and UHF paging',
    summary:
      'The faster paging standard, at 1600 and 3200 baud in two and four level, read into the same message list as POCSAG.',
    body: [
      'FLEX is what the larger paging networks moved to, and it interleaves frames so several pagers share the air efficiently. Two level at 1600 baud and four level at 3200 are both read.',
      'Messages arrive in the message view beside POCSAG, with the same deduplication, so a site running both standards reads as one stream rather than two.',
    ],
    fields: [
      'Capcode and frame position',
      'Message text',
      'Baud rate and modulation level',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Messages', 'Devices'],
    cli: '<span class="c">$</span> waveshark --tune 929.6 --mode nfm --messages',
    related: ['pocsag', 'two-tone', 'mdc1200'],
    band: 'business-vhf-uhf',
  },
  {
    slug: 'two-tone',
    name: 'Two-tone paging',
    aka: 'Quick Call II, fire pager tones, alerting tones',
    kicker: 'VHF and UHF fire and ambulance',
    summary:
      'The pair of tones that opens a fire or ambulance pager, named from an operator list so a call reads as a station rather than two frequencies.',
    body: [
      'Before any of the digital standards, and still in daily use, a volunteer fire pager is opened by two audio tones in sequence: a long one and a short one, at frequencies unique to that station. Hearing the pair is knowing which crew was just toned out.',
      'WaveShark measures the pair and looks it up in a list you provide, so the alert appears with a name. The voice dispatch that follows the tones is a call on the same channel, recorded and transcribed like any other.',
    ],
    fields: [
      'The two tone frequencies and their durations',
      'The station name, from your own list',
      'The time of the alert, and the channel',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Messages', 'Calls'],
    cli: '<span class="c">$</span> waveshark --tune 154.265 --mode nfm --calls',
    related: ['pocsag', 'mdc1200', 'p25'],
    band: 'business-vhf-uhf',
  },
  {
    slug: 'mdc1200',
    name: 'MDC-1200',
    aka: 'Motorola unit id, PTT ID, emergency button',
    kicker: 'Analogue VHF and UHF',
    summary:
      'The burst a Motorola radio sends when its key goes down, naming the unit, so an analogue channel gains who as well as what.',
    body: [
      'MDC-1200 is the short data burst at the start or end of an analogue over. It carries a unit id, and sometimes an emergency or status code, which turns an unidentified voice channel into a roster of radios.',
      'Read alongside the DTMF unit numbers and the CTCSS tone or DCS code the same channel carries, which together say which radio keyed up and which group it belongs to.',
    ],
    fields: [
      'Unit id, in hex as the fleet map writes it',
      'Operation: push to talk, emergency, status or acknowledgement',
      'The channel and the time it keyed',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Calls', 'Devices', 'Messages'],
    cli: '<span class="c">$</span> waveshark --tune 453.5 --mode nfm --calls',
    related: ['two-tone', 'dmr', 'p25'],
    band: 'business-vhf-uhf',
  },
  {
    slug: 'eas',
    name: 'EAS and SAME',
    aka: 'NOAA Weather Radio, emergency alert, 162.400 MHz',
    kicker: '162.400-162.550 MHz',
    summary:
      'Alert headers off the seven NOAA Weather Radio channels: the event, the counties it covers and how long it lasts.',
    body: [
      'A SAME header is the burst of data at the front of a weather radio alert, and it says exactly what the alert is, which county codes it applies to, when it was issued and when it expires. That is the whole alert in machine-readable form before the announcer says a word.',
      'All seven weather radio channels are placed, so the receiver finds the one your transmitter uses rather than waiting for you to guess.',
    ],
    fields: [
      'Originator and event code, expanded to its name',
      'The FIPS county codes covered',
      'Issue time and purge time',
      'The station identifier at the end of the header',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Messages', 'Calls'],
    cli: '<span class="c">$</span> waveshark --tune 162.55 --mode nfm --messages',
    related: ['pocsag', 'two-tone', 'wefax'],
    band: 'marine-vhf',
  },
  {
    slug: 'rtty',
    name: 'RTTY',
    aka: 'radioteletype, Baudot, 45.45 baud',
    kicker: 'HF and VHF',
    summary:
      'Baudot teleprinter text from 45.45 to 200 baud, either way up, read into the message view as it arrives.',
    body: [
      'RTTY is two tones and a five bit code, and it has outlived every prediction of its death: amateur contests, weather bulletins and a fair amount of utility traffic still use it. WaveShark reads the standard speeds and both polarities, so a reversed shift is not a dead channel.',
      'On a radio that transmits, an over can be keyed back out, which makes the same window both sides of a contact.',
    ],
    fields: [
      'The decoded text, live as the characters arrive',
      'Baud rate and shift',
      'Polarity, so a reversed signal is labelled rather than mangled',
    ],
    hardware: 'RTL-SDR with an upconverter for HF, or direct sampling',
    views: ['Messages', 'Spectrum'],
    cli: '<span class="c">$</span> waveshark --tune 14.085 --mode usb --messages',
    related: ['morse', 'aprs', 'wefax'],
    band: 'hf',
  },
  {
    slug: 'morse',
    name: 'Morse',
    aka: 'CW decoder, QRS, beacon',
    kicker: 'HF, VHF and UHF',
    summary:
      'A CW channel read as text at whatever speed it was sent, including the beacons that identify a repeater or a transmitter site.',
    body: [
      'Morse is still how a repeater identifies itself, how a propagation beacon announces its callsign and how a large part of the amateur bands operate. The decoder follows the sending speed rather than being told it.',
      'Text lands in the message view with everything else carrying words, which is the point: a beacon identifier and a pager message are the same kind of record.',
    ],
    fields: [
      'The decoded text',
      'Words per minute, as measured',
      'The channel and the level it was heard at',
    ],
    hardware: 'Any RTL-SDR; HF needs an upconverter or direct sampling',
    views: ['Messages', 'Spectrum'],
    cli: '<span class="c">$</span> waveshark --tune 14.058 --mode cw --messages',
    related: ['rtty', 'aprs', 'sstv'],
    band: 'hf',
  },
  {
    slug: 'dmr',
    name: 'DMR',
    aka: 'MOTOTRBO, Tier II, talkgroup, DMR ID',
    kicker: '136-174 / 400-470 MHz',
    summary:
      'Who called whom on which talkgroup, on both time slots, with speech through a source build carrying the ambe feature.',
    body: [
      'DMR puts two conversations in one 12.5 kHz channel by splitting it in time, and every burst names the caller, the group and the slot. That metadata is the useful half: a fleet becomes a list of radio ids and the groups they talk on, without a word of speech being decoded.',
      'Speech itself needs the AMBE vocoder, whose algorithms are patent encumbered, so the published builds leave it out. A build from source with the <code>ambe</code> feature decodes it. Without that feature the call still appears with its caller, its group and its length.',
      'Checked against off-air captures, asserted against what the transmission itself says rather than against another decoder.',
    ],
    fields: [
      'Source and destination radio id, and whether it is a group or private call',
      'Talkgroup, colour code and time slot',
      'Call length, and whether the call is enciphered',
      'Speech, with a source build carrying the ambe feature',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Calls', 'Keys', 'Transcript'],
    cli: '<span class="c">$</span> waveshark --tune 439.4 --calls',
    gap: 'Speech needs a source build with the ambe feature; the published binaries decode everything but the audio.',
    related: ['p25', 'nxdn', 'tetra', 'm17'],
    band: 'business-vhf-uhf',
  },
  {
    slug: 'p25',
    name: 'P25 phase 1',
    aka: 'APCO-25, trunking, talkgroup, radio id',
    kicker: '136-174 / 400-470 / 700-800 MHz',
    summary:
      'The talkgroup, the radio id and the key a call is under, off the C4FM frames North American public safety runs on.',
    body: [
      'P25 phase 1 frames carry the talkgroup and the source radio id in clear whether or not the voice payload is encrypted, which means the pattern of who talks to whom is readable on a system you cannot listen to.',
      'Where a call is encrypted, the algorithm id and key id are read and the call is listed in the keys view rather than silently dropped. An unencrypted system shows the same rows with the audio attached.',
    ],
    fields: [
      'Talkgroup and source radio id',
      'NAC, the network access code identifying the system',
      'Algorithm id and key id on an encrypted call',
      'Call length and the channel it ran on',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Calls', 'Keys'],
    cli: '<span class="c">$</span> waveshark --tune 453.5 --calls',
    gap: 'No speech yet: the frames are read for who and what, not for audio.',
    related: ['dmr', 'nxdn', 'mdc1200'],
    band: 'business-vhf-uhf',
  },
  {
    slug: 'nxdn',
    name: 'NXDN',
    aka: 'IDAS, NEXEDGE, 6.25 kHz narrowband',
    kicker: '12.5 and 6.25 kHz channels',
    summary:
      'The system number, who called whom, and whether the speech on a channel is enciphered.',
    body: [
      'NXDN is the Icom and Kenwood narrowband standard, common on business and transport systems, and it fits in half the channel DMR uses. Both channel widths are read.',
      'As with the other digital voice standards, the identities are the part that survives encryption: a radio id and a group id say what the fleet is doing even when the payload does not open.',
    ],
    fields: [
      'RAN, the system number',
      'Source and destination unit id',
      'Channel width, 12.5 or 6.25 kHz',
      'Whether the call is enciphered',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Calls', 'Keys'],
    cli: '<span class="c">$</span> waveshark --tune 467.5 --calls',
    gap: 'No speech yet.',
    related: ['dmr', 'p25', 'tetra'],
    band: 'business-vhf-uhf',
  },
  {
    slug: 'tetra',
    name: 'TETRA',
    aka: 'TEA1, TEA2, TETRAPOL alternative, trunked',
    kicker: '390-400 MHz',
    summary:
      'The network, its cells and who is called, with a wgpu key search on the ciphers in a source build carrying the tea feature.',
    body: [
      'TETRA is the European standard for public safety and transport, and its broadcasts name the network, the cell and the neighbours a radio could move to. Call setup names who is being called, which makes a busy system readable as a structure rather than a wall of noise.',
      'The keys view lists every enciphered channel and what is known about its key. The <code>tea</code> feature, in a source build only, links the ciphers and a key search that runs on any GPU through wgpu, so an enciphered channel can be worked on rather than only counted.',
      'Checked against off-air captures, asserted against what the transmission itself says.',
    ],
    fields: [
      'Mobile country and network code, and the cell',
      'Called and calling identities on call setup',
      'Which security class the cell is running',
      'The cipher in use, in the keys view',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Calls', 'Keys', 'Data links'],
    cli: '<span class="c">$</span> waveshark --tune 395 --calls',
    gap: 'Decryption and key recovery need a source build with the tea feature. The monitor is always there.',
    related: ['dmr', 'p25', 'gsm'],
    band: 'uhf-400',
  },
  {
    slug: 'm17',
    name: 'M17',
    aka: 'Codec 2, open digital voice, amateur',
    kicker: 'Amateur VHF and UHF',
    summary:
      'The open digital voice mode, decoded in full: callsigns, packet messages and Codec 2 speech, with nothing patent encumbered in the way.',
    body: [
      'M17 was designed to be implementable without licensing anything, which is why it is the one digital voice mode here that decodes to audio in the published builds. Callsigns are carried in the stream rather than as numeric ids, so a call reads as two people rather than two numbers.',
      'Packet mode carries text and arbitrary data, and those arrive in the message view in full.',
      'Checked against off-air captures, asserted against what the transmission itself says.',
    ],
    fields: [
      'Source and destination callsign',
      'Stream or packet mode, and the call length',
      'Codec 2 speech, decoded and playable',
      'Packet payloads, including text messages',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Calls', 'Messages', 'Transcript'],
    cli: '<span class="c">$</span> waveshark --tune 433.475 --calls',
    related: ['dmr', 'aprs', 'meshtastic'],
    band: 'amateur-vhf-uhf',
  },
  {
    slug: 'gsm',
    name: 'GSM',
    aka: '2G, GSM900, DCS1800, BCCH, IMSI paging',
    kicker: '900 / 1800 MHz',
    summary:
      'A cell’s identity off its synchronisation burst, the system information it broadcasts, and who a page is calling.',
    body: [
      'A GSM base station transmits continuously on its beacon channel, and everything needed to identify it is in clear: the country and network codes, the cell id, the location area and the neighbours it advertises. That is a survey of the mobile infrastructure around you from a receiver that never transmits.',
      'Paging messages name the subscriber identity being called and the channel a phone is then directed to. Traffic itself is encrypted and is not decoded.',
    ],
    fields: [
      'MCC, MNC, LAC and cell id',
      'System information blocks, including the neighbour list',
      'Paging requests and the identity paged',
      'Immediate assignment: the channel a phone is sent to',
    ],
    hardware: 'RTL-SDR for 900 MHz; 1800 MHz wants a HackRF or LimeSDR',
    views: ['Data links', 'Devices'],
    cli: '<span class="c">$</span> waveshark --tune 941 --span 2000 --links',
    gap: 'Voice and data on a traffic channel are encrypted and stay that way.',
    related: ['tetra', 'wifi', 'ble'],
    band: 'gsm',
  },
  {
    slug: 'meshtastic',
    name: 'LoRa mesh',
    aka: 'Meshtastic, MeshCore, LoRaWAN, chirp spread spectrum',
    kicker: '433 / 868 / 915 MHz',
    summary:
      'Meshtastic text under the public keys, MeshCore adverts, and LoRaWAN join requests with the addresses they allocate.',
    body: [
      'LoRa is a chirp, which is why it works at levels below the noise floor and why a conventional scanner never sees it. WaveShark places the chirp decoder on the ISM bands and reads what the three common stacks put on top of it.',
      'Meshtastic channels with the default key decode to text; ones with their own key show the node, the hops and the packet type without the words. MeshCore adverts name the nodes announcing themselves. LoRaWAN join requests carry the device EUI, which identifies the sensor even when its payload is encrypted.',
    ],
    fields: [
      'Node id, hop limit and the channel hash',
      'Message text where the channel key allows it',
      'LoRaWAN device EUI, join EUI and device address',
      'Spreading factor, bandwidth and coding rate',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Messages', 'Map', 'Devices'],
    cli: '<span class="c">$</span> waveshark --tune 869.525 --messages',
    related: ['wmbus', 'ism', 'aprs'],
    band: '868-mhz',
  },
  {
    slug: 'wmbus',
    name: 'Wireless M-Bus',
    aka: 'wM-Bus mode T, smart meter, OMS, 868.95 MHz',
    kicker: '868.95 MHz',
    summary:
      'The heat, water, gas and electricity meters transmitting around you: manufacturer, meter number, version and type.',
    body: [
      'Wireless M-Bus mode T is what most European utility meters use to report themselves to a drive-by or fixed collector. Every meter identifies itself in clear even where the readings are encrypted, so a block of flats resolves into a list of meters by manufacturer and serial.',
      'Feed the ones that are yours into Home Assistant with <code>--ha-broker</code> and <code>--ha-spaces ism,wmbus</code>, and the reading appears as a sensor with no vendor gateway involved.',
    ],
    fields: [
      'Manufacturer code and meter serial number',
      'Device type: water, heat, gas or electricity',
      'Version, and the access number that increments per transmission',
      'Readings where the meter sends them unencrypted',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Devices', 'Data links'],
    cli: '<span class="c">$</span> waveshark --tune 868.95 --ha-broker homeassistant.local --ha-spaces wmbus',
    related: ['ert', 'ism', 'zwave'],
    band: '868-mhz',
  },
  {
    slug: 'ert',
    name: 'Itron ERT meters',
    aka: 'SCM, SCM+, IDM, rtlamr, 915 MHz meter',
    kicker: '915 MHz',
    summary:
      'North American utility meters: the consumption number, the meter id and the type, in SCM, SCM+ and IDM formats.',
    body: [
      'Itron ERT endpoints are on gas, water and electricity meters across North America, transmitting a consumption total every few seconds so a passing van or a fixed collector can read the street without anybody walking it.',
      'The three message formats are read: SCM and SCM+ carry the running total, and IDM adds interval data. The meter id is stable, which is what makes a meter a device rather than a sighting.',
    ],
    fields: [
      'Meter id and endpoint type',
      'Consumption total, as the meter counts it',
      'Tamper flags for the physical and encoder switches',
      'Message format: SCM, SCM+ or IDM',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Devices', 'Data links'],
    cli: '<span class="c">$</span> waveshark --tune 915 --span 2400 --survey',
    related: ['wmbus', 'ism', 'tpms'],
    band: '915-mhz',
  },
  {
    slug: 'zwave',
    name: 'Z-Wave',
    aka: 'door lock, smart home, 868.42 MHz, 908.42 MHz',
    kicker: '868 / 908 MHz',
    summary:
      'Door locks, sensors and plugs at 9.6, 40 and 100 kbit/s, on the European and North American channels.',
    body: [
      'Z-Wave sits below the Zigbee crowd at sub-gigahertz, which is why it goes through walls better and why it never shows up on a 2.4 GHz survey. All three data rates are read, so an old sensor at 9.6 kbit/s appears beside a new lock at 100.',
      'Frames name the home id and the node, which is enough to count the devices in a home network and see which of them are talking, whether or not the payload is secured.',
    ],
    fields: [
      'Home id and source and destination node ids',
      'Frame type and the command class where it is in clear',
      'Data rate, and the channel',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Devices', 'Data links', 'Channels'],
    cli: '<span class="c">$</span> waveshark --tune 868.42 --span 400',
    related: ['zigbee', 'ism', 'wmbus'],
    band: '868-mhz',
  },
  {
    slug: 'ism',
    name: 'ISM sensors and remotes',
    aka: 'rtl_433, 433.92 MHz, weather station, door sensor',
    kicker: '433 / 868 / 915 MHz',
    summary:
      '45 decoders from the rtl_433 family: weather stations, thermometers, door contacts, gate remotes, security sensors and shelf labels.',
    body: [
      'This is the band most people start on, and the devices on it are the ones nobody thinks of as radio: the outdoor thermometer, the doorbell, the gate remote, the shelf label in a supermarket. Almost all of them carry a stable device id, which is what turns a survey into a list of devices rather than a list of transmissions.',
      'Coverage is the thin part and the site will not pretend otherwise: rtl_433 has roughly 250 device decoders and WaveShark has forty-five, verified field for field against rtl_433 25.02 on 81 recordings from its corpus. A burst nothing claims is still kept, with its coding inferred and its bits sliced out.',
    ],
    fields: [
      'Device model and id, stable across transmissions',
      'Temperature, humidity, rain and wind where the sensor sends them',
      'Battery flag, channel and the button pressed on a remote',
      'Raw timings and bits for anything unclaimed',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Devices', 'Data links', 'Spectrum'],
    cli: '<span class="c">$</span> waveshark --tune 433.92 --survey',
    related: ['tpms', 'wmbus', 'zwave', 'ert'],
    band: '433-mhz',
  },
  {
    slug: 'tpms',
    name: 'TPMS',
    aka: 'tyre pressure sensor, Ford, Renault, Schrader, 315 MHz',
    kicker: '315 / 433.92 MHz',
    summary:
      'Tyre pressure sensors as cars pass: the sensor id, the pressure, the temperature and whether the wheel is turning.',
    body: [
      'Every car built in the last decade has four radios in its wheels, each transmitting an id that does not change for the life of the sensor. That makes TPMS the most reliable way to recognise a vehicle passing a fixed point, which is exactly why it is worth knowing it is happening.',
      'Ford and Renault sensors are decoded along with the generic families, with pressure and temperature where the sensor sends them. Europe uses 433.92 MHz and North America 315 MHz.',
    ],
    fields: [
      'Sensor id, unique per wheel',
      'Pressure and temperature',
      'Moving or stationary, where the sensor says',
      'Battery and fault flags',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Devices', 'Map'],
    cli: '<span class="c">$</span> waveshark --tune 433.92 --survey --location 53.34,-6.26',
    related: ['ism', 'ert', 'remote-id'],
    band: '433-mhz',
  },
  {
    slug: 'ble',
    name: 'Bluetooth LE',
    aka: 'BLE advertising, Bluetooth 5 Long Range, iBeacon',
    kicker: '2.4 GHz advertising channels',
    summary:
      'Advertising packets on all three primary channels, Bluetooth 5 Long Range included, with Open Drone ID read where it is carried.',
    body: [
      'Every phone, watch, tag and speaker in range advertises on three channels, and those advertisements carry names, service ids and manufacturer data. Most modern devices rotate their address every fifteen minutes or so, which the devices view reports rather than hides.',
      'Coded PHY, the Bluetooth 5 long range mode, is read as well, which matters because it is what the longer-range trackers and industrial sensors use.',
    ],
    fields: [
      'Advertising address, and whether it is randomised',
      'Local name, service UUIDs and manufacturer data',
      'PHY and the advertising channel',
      'Open Drone ID, where a drone carries it over BLE',
    ],
    hardware: 'HackRF or LimeSDR: an advertising channel is 2 MHz wide',
    views: ['Devices', 'Channels', 'Map'],
    cli: '<span class="c">$</span> waveshark --tune 2426 --span 4000 --survey',
    related: ['wifi', 'zigbee', 'remote-id'],
    band: '2-4-ghz',
  },
  {
    slug: 'wifi',
    name: 'Wi-Fi',
    aka: '802.11, beacon frames, SSID, probe request',
    kicker: '2.4 GHz',
    summary:
      '802.11a/g/b and single-stream n: network names, the addresses talking, the rate each frame arrived at and whether an address is randomised.',
    body: [
      'A Wi-Fi channel is 20 MHz wide, so reading one is a job for a HackRF or a LimeSDR rather than a dongle. What comes out is a survey: the networks beaconing, the clients probing, the rates in use and the addresses that keep appearing.',
      'The channels view says how crowded each channel is, which is the practical answer to where to put your own network. The devices view keeps one row per address with the strongest level it was ever heard at, and a drive exports as WiGLE CSV.',
    ],
    fields: [
      'SSID from beacons and probe responses',
      'Transmitter and receiver addresses, with randomisation flagged',
      'Data rate per frame, and the channel',
      'Frame type: management, control or data',
    ],
    hardware: 'HackRF One or LimeSDR',
    views: ['Devices', 'Channels', 'Data links'],
    cli: '<span class="c">$</span> waveshark --tune 2437 --span 20000 --channels',
    related: ['ble', 'zigbee', 'remote-id'],
    band: '2-4-ghz',
  },
  {
    slug: 'zigbee',
    name: 'Zigbee, Thread and Matter',
    aka: 'IEEE 802.15.4, PAN id, smart home mesh',
    kicker: '2.4 GHz channels 11-26',
    summary:
      'The 802.15.4 layer under all three stacks: the addresses talking, the networks they belong to and the channel each sits on.',
    body: [
      'Zigbee, Thread and Matter over Thread all ride on IEEE 802.15.4, so one decoder sees all of them. What is readable is the network layer: PAN ids, short and extended addresses, and which devices are routing for which.',
      'On a crowded 2.4 GHz band the channels view is the useful pairing, because 802.15.4 channels overlap Wi-Fi ones and a mesh that keeps dropping is usually sitting under an access point.',
    ],
    fields: [
      'PAN id, and source and destination addresses',
      'Frame type: beacon, data, acknowledgement or command',
      'Channel and link quality',
      'Sequence numbers, which show retries',
    ],
    hardware: 'HackRF or LimeSDR',
    views: ['Devices', 'Channels', 'Data links'],
    cli: '<span class="c">$</span> waveshark --tune 2440 --span 4000 --channels',
    related: ['ble', 'zwave', 'wifi'],
    band: '2-4-ghz',
  },
  {
    slug: 'remote-id',
    name: 'Drone Remote ID',
    aka: 'DJI DroneID, Open Drone ID, ASTM F3411, operator location',
    kicker: '2.4 GHz',
    summary:
      'A drone’s serial, position, height and operator location, from the Remote ID broadcast it is required to send, and the home point from a DJI airframe.',
    body: [
      'Remote ID is a broadcast, not a network service: the aircraft transmits who it is and where it and its operator are, over Wi-Fi or Bluetooth LE, and anything nearby can read it. WaveShark reads Open Drone ID on both carriers and puts the aircraft and the operator on the map as separate marks.',
      'DJI airframes also broadcast DJI DroneID, which adds the home point, meaning the place the aircraft took off from. That needs 15.36 MS/s, so it is a HackRF or LimeSDR job rather than a dongle one.',
    ],
    fields: [
      'Serial number as printed on the airframe',
      'Position, height, speed and heading',
      'Operator position, where the aircraft has a fix',
      'Home point, on DJI DroneID',
    ],
    hardware: 'HackRF One or LimeSDR',
    views: ['Map', 'Devices', 'Control'],
    cli: '<span class="c">$</span> waveshark --tune 2437 --span 20000 --location 53.34,-6.26',
    related: ['rc-links', 'wifi', 'ble'],
    band: '2-4-ghz',
  },
  {
    slug: 'rc-links',
    name: 'RC control links',
    aka: 'ExpressLRS, FrSky ACCST, FlySky AFHDS-2A, XN297',
    kicker: '2.4 GHz / 868 / 915 MHz',
    summary:
      'Where the sticks are on every model control link in earshot: a bar per channel in microseconds, with the frame rate and whether the handset is asking to arm.',
    body: [
      'A control link is the one signal that says what the pilot is doing rather than what the aircraft is. The control view draws each channel as a bar in microseconds, live, with the packet rate and the link level beside it, and flags the arm switch.',
      'ExpressLRS is the link the receiver places for itself, on 2.4 GHz and on the 868 and 915 MHz bands. FrSky ACCST, FlySky AFHDS-2A and XN297 toy remotes are read as well, the last with its address and payload.',
    ],
    fields: [
      'Channel positions in microseconds, live',
      'Packet rate and link level',
      'Arm request, where the protocol carries it',
      'Binding phrase hash or address, depending on the link',
    ],
    hardware: 'HackRF or LimeSDR at 2.4 GHz; a dongle on 868 and 915',
    views: ['Control', 'Devices', 'Spectrum'],
    cli: '<span class="c">$</span> waveshark --tune 2440 --span 20000 --control',
    related: ['remote-id', 'meshtastic', 'fpv-video'],
    band: '2-4-ghz',
  },
  {
    slug: 'sstv',
    name: 'SSTV',
    aka: 'slow scan television, Martin, Scottie, Robot 36',
    kicker: '144.500 MHz and HF',
    summary:
      'Pictures drawn line by line as they arrive, in Martin 1 and 2, Scottie 1, 2 and DX, and Robot 36 and 72, saved to disc when the transmission ends.',
    body: [
      'SSTV sends a picture as audio over a voice channel, a line at a time, over a minute or two. Watching it build is half the appeal, so the video view draws each line as it lands rather than waiting for the end, and the caption counts the lines received.',
      'Every finished picture is written to <code>~/.local/share/waveshark/pictures</code>. On a radio that transmits, a picture can be sent back out in the same modes.',
      'Checked against colaclanth’s decoder on the same recordings.',
    ],
    fields: [
      'The picture itself, line by line',
      'Mode, detected from the VIS header',
      'Lines received, so a partial picture is labelled as one',
      'The channel and the time it started',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Video', 'Calls'],
    cli: '<span class="c">$</span> waveshark --tune 144.5 --mode usb --video',
    related: ['apt', 'lrpt', 'wefax', 'fpv-video'],
    band: 'amateur-vhf-uhf',
  },
  {
    slug: 'apt',
    name: 'NOAA APT',
    aka: 'weather satellite images, NOAA 15, NOAA 18, NOAA 19, 137 MHz',
    kicker: '137.1 / 137.9125 / 137.62 MHz',
    summary:
      'Analogue weather satellite pictures from the NOAA birds, drawn as the pass comes over, with the pass itself planned in the satellites view.',
    body: [
      'APT is the oldest thing on this site and still the most satisfying: two visible and infrared channels sent as an audio-rate picture from a satellite passing overhead, and a picture of your own weather on the screen fifteen minutes later.',
      'The satellites view lists the passes over your station for the next day with peak elevation and a sky plot, then follows the downlink through Doppler for the whole pass and closes the channel when the satellite sets. Nobody has to sit at the dial.',
    ],
    fields: [
      'The picture, both channels, as the pass builds',
      'Which satellite, and its pass geometry',
      'Lines received, and the sync quality',
    ],
    hardware: 'Any RTL-SDR, with a turnstile or V-dipole',
    views: ['Satellites', 'Video', 'Map'],
    cli: '<span class="c">$</span> waveshark --tune 137.1 --mode wfm --video',
    related: ['lrpt', 'wefax', 'radiosondes'],
    band: '137-mhz',
  },
  {
    slug: 'lrpt',
    name: 'Meteor-M LRPT',
    aka: 'Meteor M2, MSU-MR, digital weather satellite',
    kicker: '137 MHz',
    summary:
      'The Russian digital weather satellite: three MSU-MR channels drawn a strip of eight rows at a time as the pass comes over.',
    body: [
      'LRPT is the digital counterpart to APT, and the picture is sharper for it. The three MSU-MR channels arrive interleaved and are drawn on the video pane in strips as the frames are assembled, so a pass builds visibly rather than appearing at the end.',
      'The same pass planning applies: the satellites view has the pass, and the receiver follows the Doppler shift across it without being touched.',
    ],
    fields: [
      'Three MSU-MR channels as they arrive',
      'Frame and packet counts, so a poor pass is obvious',
      'The satellite and the pass it came from',
    ],
    hardware: 'Any RTL-SDR, with a turnstile or QFH antenna',
    views: ['Satellites', 'Video'],
    cli: '<span class="c">$</span> waveshark --tune 137.1 --video',
    related: ['apt', 'wefax', 'radiosondes'],
    band: '137-mhz',
  },
  {
    slug: 'wefax',
    name: 'HF weather fax',
    aka: 'radiofax, WEFAX, marine charts, Northwood',
    kicker: 'Shortwave',
    summary:
      'Surface pressure charts and ice maps sent to shipping on shortwave, drawn on the video pane as they come in.',
    body: [
      'Weather fax is a chart sent as a slow picture over a single sideband channel, still broadcast for shipping by several national services. A full chart takes several minutes and appears line by line.',
      'It shares the video pane with SSTV and the satellite passes, because a picture is a picture whatever carried it.',
    ],
    fields: [
      'The chart itself, as it draws',
      'Line rate and index of cooperation',
      'Start and stop tones, so a chart is cut where it should be',
    ],
    hardware: 'RTL-SDR with an upconverter, or an HF-capable radio',
    views: ['Video', 'Spectrum'],
    cli: '<span class="c">$</span> waveshark --tune 4.610 --mode usb --video',
    related: ['apt', 'sstv', 'eas'],
    band: 'hf',
  },
  {
    slug: 'radiosondes',
    name: 'Radiosondes',
    aka: 'RS41, DFM, M10, iMet, weather balloon, SondeHub',
    kicker: '400-406 MHz',
    summary:
      'Weather balloons on the map with serial, height and climb rate, in eight families, with the channel following the transmitter as it drifts.',
    body: [
      'Two balloons go up from most launch sites every day, climb to around 30 km and burst, and each one transmits its position and the air it is measuring the whole way. Chasing and recovering them is a hobby of its own, and the flight is public data while it is in the air.',
      'Vaisala RS41, Graw DFM, Meteomodem M10 and M20, InterMet iMet, Meisei iMS-100, Meteo-Radiy MRZ and Lockheed Martin LMS6 are all read. A sonde drifts in frequency as it climbs and cools, so the channel follows it rather than losing it at 20 km.',
      'SondeHub launch sites are drawn on the map with the time until the next release, so you know when to be listening. Checked against SDRangel on the same recording.',
    ],
    fields: [
      'Serial number, as printed on the sonde',
      'Position, height and climb rate',
      'Air temperature and humidity, where the sonde measures them',
      'Frame number and battery, which tell you how the flight is going',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Map', 'Devices', 'Spectrum'],
    cli: '<span class="c">$</span> waveshark --tune 403 --span 2400 --location 53.34,-6.26',
    related: ['apt', 'epirb', 'lrpt'],
    band: 'uhf-400',
  },
  {
    slug: 'dvbt',
    name: 'DVB-T television',
    aka: 'digital terrestrial, transport stream, Freeview, multiplex',
    kicker: 'UHF',
    summary:
      'A multiplex read from its carriers down to its transport stream, with the service you pick playing in the window at full frame rate and its sound in step.',
    body: [
      'This is the deepest decode on the site: an 8 MHz OFDM multiplex demodulated, the transport stream recovered, the service tables read and a programme decoded to picture and sound. The transmission parameters it reports are the ones a broadcast engineer would ask for.',
      'Only the macOS build shows the picture, because it is the only one whose ffmpeg is new enough; the others read the multiplex and list its services. Transmitting a multiplex works the other way, from a transport stream file or anything ffmpeg can open.',
    ],
    fields: [
      'Constellation, guard interval, code rate and cell id',
      'The services on the multiplex, with their names and types',
      'The chosen service, playing, with audio in sync',
      'Bit rate and error counts',
    ],
    hardware: 'HackRF or LimeSDR: a multiplex is 8 MHz wide',
    views: ['Video', 'Spectrum', 'Data links'],
    cli: '<span class="c">$</span> waveshark --tune 474 --span 8000 --video',
    gap: 'Pictures off a multiplex play on the macOS build only; elsewhere the services are listed but not decoded.',
    related: ['dab', 'drm', 'fpv-video'],
    band: 'uhf-tv',
  },
  {
    slug: 'dab',
    name: 'DAB',
    aka: 'DAB+, digital radio, ensemble, band III',
    kicker: 'Band III',
    summary:
      'An ensemble and the stations in it, with their programme types and bit rates, read off the block your transmitter uses.',
    body: [
      'A DAB ensemble is a bundle of stations sharing one transmission, and reading it tells you what is in the bundle: the ensemble name, every service on it, what kind of programme each is and how many kilobits it has been given, which is the number that decides how it sounds.',
      'The blocks are named on the spectrum, so 11C reads as 11C rather than as a frequency to look up.',
    ],
    fields: [
      'Ensemble name and id',
      'Service names and programme types',
      'Bit rate and protection level per service',
      'The block, named from the band plan',
    ],
    hardware: 'Any RTL-SDR',
    views: ['Spectrum', 'Data links', 'Channels'],
    cli: '<span class="c">$</span> waveshark --tune 222.064 --span 2000',
    gap: 'No sound yet: the ensemble is read for what it carries, not decoded to audio.',
    related: ['drm', 'dvbt', 'fpv-video'],
    band: 'band-iii',
  },
  {
    slug: 'drm',
    name: 'DRM',
    aka: 'Digital Radio Mondiale, shortwave digital, medium wave',
    kicker: 'Shortwave and medium wave',
    summary:
      'The services in a DRM multiplex, their languages and their labels, off a shortwave or medium wave transmission.',
    body: [
      'DRM is digital broadcasting in the bands that reach across continents, which is why it is still used by international broadcasters where nothing else carries. A multiplex holds one to four services, each with a language and a label.',
      'What is read here is the multiplex structure rather than the audio: which services exist, in which languages, and how the transmission is configured.',
    ],
    fields: [
      'Services in the multiplex, with labels and languages',
      'Robustness mode and spectrum occupancy',
      'Service identifiers',
    ],
    hardware: 'RTL-SDR with an upconverter, or an HF-capable radio',
    views: ['Spectrum', 'Data links'],
    cli: '<span class="c">$</span> waveshark --tune 3.965 --span 100',
    gap: 'No sound yet.',
    related: ['dab', 'dvbt', 'wefax'],
    band: 'hf',
  },
  {
    slug: 'fpv-video',
    name: 'Analogue video and FPV',
    aka: 'PAL, NTSC, 5.8 GHz FPV, wireless camera',
    kicker: '1.2 / 2.4 / 5.8 GHz',
    summary:
      'A camera’s picture straight off the span, PAL or NTSC in colour, with its audio subcarrier heard alongside and the carrier named from its line rate.',
    body: [
      'Analogue video links are still everywhere: cheap wireless cameras, baby monitors, and every FPV quadcopter on 5.8 GHz. There is nothing to decrypt and nothing that checks itself, which is why the caption counts the lines received rather than claiming a good picture.',
      'An FPV carrier is named from its line rate and given its channel in the usual band naming, so it reads as R1, F4 or A5 rather than as a frequency. The audio subcarrier, 6.5 MHz on the recording this was built against, is heard with the picture, because a picture with no sound is half a receiver.',
    ],
    fields: [
      'The picture, in colour, PAL or NTSC',
      'Line rate, and the FPV channel it corresponds to',
      'Lines received per frame',
      'The audio subcarrier, played alongside',
    ],
    hardware: 'HackRF or LimeSDR',
    views: ['Video', 'Spectrum', 'Channels'],
    cli: '<span class="c">$</span> waveshark --tune 5800 --span 20000 --video',
    related: ['dvbt', 'sstv', 'rc-links'],
    band: '5-8-ghz',
  },
];
